# Generated by Django 2.0 on 2018-05-16 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='e-mail address')),
                ('user_name', models.CharField(blank=True, max_length=128, verbose_name='user Name')),
                ('password', models.CharField(blank=True, max_length=128, verbose_name='pass word')),
                ('icon', models.CharField(blank=True, max_length=128, verbose_name='user icon image')),
                ('create_date', models.DateField(auto_now_add=True)),
                ('last_login', models.DateField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
