# Generated by Django 2.0 on 2018-05-17 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ginstagram', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
    ]
