# Generated by Django 2.0 on 2018-05-17 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ginstagram', '0003_auto_20180517_0513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='icon',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='user icon image'),
        ),
        migrations.AlterField(
            model_name='users',
            name='last_login',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=128, verbose_name='pass word'),
        ),
    ]
